{% set name = "nano-vectordb" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nano_vectordb-{{ version }}.tar.gz
  sha256: 4da362471fd3a52c8ad49b66f4e0a76c3e9dca09524eeb8221aa819f2d328b02
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy

test:
  imports:
    - nano_vectordb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gusye1234/nano-vectordb
  summary: A simple, easy-to-hack Vector Database implementation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
