{% set name = "nano-vectordb" %}
{% set version = "0.0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nano_vectordb-{{ version }}.tar.gz
  sha256: 24f4c6cb35f6300a6c5ce344ea8deb6b016e0d88c1b4b6b1fc18d88a8fb64fac
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy

test:
  imports:
    - nano_vectordb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gusye1234/nano-vectordb
  summary: A simple, easy-to-hack Vector Database implementation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
